### ISSUE TITLE
No links found

### ISSUE THREAD

**Issue by Clavisnl** [mancuniancol/script.pulsar.rarbg-mc#3] opened 2015-12-24 22:17 UTC
Hey,

Id like to use this provider. But i get an error No links found. Every other provider is working. Im using Windows as OS. I tried Android, but it works just fine on Android. Any fix? Keep up the good work.

**Comment by mancuniancol** [comment] 2015-12-24 22:24
Well, it could be the time out. Which is the value that you are using? Have you already tried to increase it?

**Comment by Clavisnl** [comment] 2015-12-24 22:30
Thanks for the quick reply. Just found this thread. Enabled it and its on 4 now. Still no luck. Ill try some different values. Ill let you know. Happy holidays!

**Comment by Clavisnl** [comment] 2015-12-24 22:35
Okay seems i find more torrents now. But i still get an error to check the log. It is on 6 seconds now

**Comment by Clavisnl** [comment] 2015-12-24 22:40
@mancuniancol still no luck. Only using rarbg now, and tried every value from 4 to 60. Just says error check log. No links found.

**Comment by mancuniancol** [comment] 2015-12-24 23:19
I will need to see your log in debug mode. Not idea without that info. Usually,  20 a 30s

**Comment by mancuniancol** [comment] 2015-12-24 23:25
Is ok.  Any case there is a forum where you can go. This is the link
http://forums.tvaddons.ag/addon-releases/31572-pulsar-providers-unofficial-pulsar-repo.html

**Comment by Clavisnl** [comment] 2015-12-25 00:19
@mancuniancol kk, ill upload a log to pastebin tomorrow.

**Comment by Clavisnl** [comment] 2015-12-25 00:20
@mancuniancol thanks For the help so far

**Comment by rarbg** [comment] 2015-12-25 10:16
@mancuniancol 
Why would he need a higher timeout when the api always responds in less than 1s ?
Im pretty sure the issue is his windows pc not being able to connect to cloudflare because of ssl for example

**Comment by mancuniancol** [comment] 2015-12-25 10:27
@rarbg, I was talking about pulsar. It has 4s, but it can only manage two or three providers at the same time.  With 20 secs I can have 15 providers without having the time out.

**Comment by rarbg** [comment] 2015-12-25 10:33
@mancuniancol 
huh i thought pulsar is async and the timeouts are per provider not a global one

**Comment by mancuniancol** [comment] 2015-12-25 10:39
Now,  you know :)

**Comment by rarbg** [comment] 2015-12-25 10:41
that on my opinion is plainly said ... stupid :D

**Comment by Clavisnl** [comment] 2015-12-25 10:42
@mancuniacol i use around 6 providers without the custom timeout. 2 days ago i configured a Android media box with pulsar and rarbg for my father in law, and it worked right away. I cant understand the log. But it might have something to do with my Windows config.

**Comment by Clavisnl** [comment] 2015-12-25 10:43
@mancuniancol

**Comment by Clavisnl** [comment] 2015-12-25 11:18
@mancuniancol heres the log. Pastebin.com/iuwC1eB5

**Comment by rarbg** [comment] 2015-12-25 11:27
Yep you deffinetly cant connect to cloudflare.
Can you try opening https://torrentapi.org/ from your browser ?

**Comment by Clavisnl** [comment] 2015-12-25 11:32
@rarbg nop. Error 403. I made a connection, but not enough rights to show the page.

**Comment by rarbg** [comment] 2015-12-25 11:46
@Clavisnl 
What about https://torrentapi.org/test.txt ?

**Comment by rarbg** [comment] 2015-12-25 11:50
Also can you please send your ip to support@rarbg.com so i can check the logs of what requests you are doing ?

**Comment by Clavisnl** [comment] 2015-12-25 11:51
@rarbg it says "works :).

**Comment by rarbg** [comment] 2015-12-25 11:51
@Clavisnl Also can you please send your ip to support@rarbg.com so i can check the logs of what requests you are doing ?

**Comment by rarbg** [comment] 2015-12-25 11:58
@Clavisnl 
Are you using the latest kodi ?

**Comment by Clavisnl** [comment] 2015-12-25 11:59
@rarbg Yea, 16.0. Had the problem with 15 aswell. Send you an email.

**Comment by rarbg** [comment] 2015-12-25 12:03
@Clavisnl  Your kodi is doing requests fine and the api is responding fine to them.
@mancuniancol is there a way to do a full debug , urls called , responses , etc ?

**Comment by mancuniancol** [comment] 2015-12-25 13:28
Clavisnl, the problem what you have it is not with the provider.  It is about Pulsar itself.  You need to check your firewall and antivirus.  BTw, your log is incomplete.  Hard to help you like that.

Please, go to this forum if you want support:
http://forums.tvaddons.ag/addon-releases/31572-pulsar-providers-unofficial-pulsar-repo.html

I will close this issue, because the provider is working well.  Sorry.

**Closed by mancuniancol** 2015-12-25 13:28 UTC
